# import sorting
[tool.isort]
# default: sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
profile = "black"
known_first_party = [
  "bpsCPdf",
  "bbsDateTime",
  "bpsFile",
  "bpsList",
  "bpsMath",
  "bpsPrettyPrint",
  "bpsString",
  "bpsTsIdxData",
]

# configure opinionated python linter
[tool.pylint.string]
check-quote-consistency = true
